In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/spotify_tracks.csv")

### About the data set
---
The data for this project is from Kaggle. The dataset is collected via the Spotify Web API. Each track comes with a rich set of audio features computed by Spotify's internal audio analysis engine. There are 114000 audio tracks (an individual audio file) and 20 variables (columns). The dataset is published by Sai Chaitanya Reddy — AI & Data Science undergraduate at Vasireddy Venkatadri International Technological University (VVIT), Hyderabad, India. This dataset is intended for educational and research purposes.

#### Limitations
The dataset description does not specify the collection period, sampling methodology, or filtering criteria. Consequently, any conclusions drawn from the analysis should be interpreted with this lack of metadata in mind.

In [3]:
df.shape

(114000, 20)

In [4]:
df.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre'],
      dtype='str')

In [5]:
df.head(20)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,0.4810,6,-8.807,1,0.1050,0.2890,0.000000,0.1890,0.6660,98.017,4,acoustic
6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.1470,2,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.4440,11,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
8,0IktbUcnAGrvD03AWnz3Q8,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,74,189613,False,0.625,0.4140,0,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
9,7k9GuJYLp2AzqokyEdwEw2,Ross Copperman,Hunger,Hunger,56,205594,False,0.442,0.6320,1,-6.770,1,0.0295,0.4260,0.004190,0.0735,0.1960,78.899,4,acoustic
10,4mzP5mHkRvGxdhdGdAH7EJ,Zack Tabudlo,Episode,Give Me Your Forever,74,244800,False,0.627,0.3630,8,-8.127,1,0.0291,0.2790,0.000000,0.0928,0.3010,99.905,4,acoustic
11,5ivF4eQBqJiVL5IAE9jRyl,Jason Mraz,Love Is a Four Letter Word,I Won't Give Up,69,240165,False,0.483,0.3030,4,-10.058,1,0.0429,0.6940,0.000000,0.1150,0.1390,133.406,3,acoustic
12,4ptDJbJl35d7gQfeNteBwp,Dan Berk,Solo,Solo,52,198712,False,0.489,0.3140,7,-9.245,0,0.0331,0.7490,0.000000,0.1130,0.6070,124.234,4,acoustic
13,0X9MxHR1rTkEHDjp95F2OO,Anna Hamilton,Bad Liar,Bad Liar,62,248448,False,0.691,0.2340,3,-6.441,1,0.0285,0.7770,0.000000,0.1200,0.2090,87.103,4,acoustic
14,4LbWtBkN82ZRhz9jqzgrb3,Chord Overstreet;Deepend,Hold On (Remix),Hold On - Remix,56,188133,False,0.755,0.7800,2,-6.084,1,0.0327,0.1240,0.000028,0.1210,0.3870,120.004,4,acoustic
15,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.5610,4,-7.933,1,0.0274,0.2000,0.000046,0.1790,0.2380,83.457,3,acoustic
16,6xKeQgzfjixSUld14qUezm,Andrew Foy;Renee Foy,ily (i love you baby),ily (i love you baby),56,129750,False,0.706,0.1120,2,-18.098,1,0.0391,0.8270,0.000004,0.1250,0.4140,110.154,4,acoustic
17,4Yo0igmcoNyat1secaH0OD,Andrew Foy;Renee Foy,At My Worst,At My Worst,54,169728,False,0.795,0.0841,10,-18.090,0,0.0461,0.7420,0.000012,0.0853,0.6090,91.803,4,acoustic
18,2qLMf6TuEC3ruGJg4SMMN6,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,68,189613,False,0.625,0.4140,0,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
19,6CgNoAbFJ4Q4Id4EjtbXlC,Boyce Avenue;Bea Miller,"Cover Sessions, Vol. 4",Photograph,67,260186,False,0.717,0.3200,3,-8.393,1,0.0283,0.8300,0.000000,0.1070,0.3220,107.946,4,acoustic

In [6]:
df.dtypes

track_id                str
artists                 str
album_name              str
track_name              str
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre             str
dtype: object

### Uniqueness of each row - Track IDs are not unique for each row
The number of unique track IDs (89741) is smaller than the total number of rows (114000), indicating that some track IDs appear multiple times. This suggests that multiple rows may correspond to the same Spotify track, although further investigation is needed to determine whether these are true duplicate records or repeated observations with different metadata.

In [7]:
len(df["track_name"].unique())

73609

In [8]:
len(df["album_name"].unique())

46590

In [9]:
len(df["track_id"].unique())

89741

In [10]:
len(df["artists"].unique())

31438

### Duplicate Track ID's

In [11]:
repeated_track_rows = df[df["track_id"].duplicated(keep=False)]
print(len(repeated_track_rows)) # There are 40900 duplicate row group

40900

In [12]:
duplicated_id_rows = df[df["track_id"].duplicated(keep="first")]
print(len(duplicated_id_rows)) # There are 24259 first occurrences of the duplicate track IDs

24259

In [13]:
print(df.duplicated(keep=False).sum()) # 894 rows belong to a completely duplicate group.

894

In [14]:
print(df.duplicated(keep="first").sum()) # 450 rows are duplicate copies beyond the first occurrence.

450

In [15]:
repeated_track_rows.head(10) # I wanted to inspect the duplicates individually to understand reasons behind the duplicate rows

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,0.4810,6,-8.807,1,0.1050,0.2890,0.000000,0.1890,0.6660,98.017,4,acoustic
6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.1470,2,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.4440,11,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
9,7k9GuJYLp2AzqokyEdwEw2,Ross Copperman,Hunger,Hunger,56,205594,False,0.442,0.6320,1,-6.770,1,0.0295,0.4260,0.004190,0.0735,0.1960,78.899,4,acoustic
12,4ptDJbJl35d7gQfeNteBwp,Dan Berk,Solo,Solo,52,198712,False,0.489,0.3140,7,-9.245,0,0.0331,0.7490,0.000000,0.1130,0.6070,124.234,4,acoustic
13,0X9MxHR1rTkEHDjp95F2OO,Anna Hamilton,Bad Liar,Bad Liar,62,248448,False,0.691,0.2340,3,-6.441,1,0.0285,0.7770,0.000000,0.1200,0.2090,87.103,4,acoustic
16,6xKeQgzfjixSUld14qUezm,Andrew Foy;Renee Foy,ily (i love you baby),ily (i love you baby),56,129750,False,0.706,0.1120,2,-18.098,1,0.0391,0.8270,0.000004,0.1250,0.4140,110.154,4,acoustic
17,4Yo0igmcoNyat1secaH0OD,Andrew Foy;Renee Foy,At My Worst,At My Worst,54,169728,False,0.795,0.0841,10,-18.090,0,0.0461,0.7420,0.000012,0.0853,0.6090,91.803,4,acoustic

In [16]:
for duplicate_id in repeated_track_rows.head(10)["track_id"]:
    display(df[df["track_id"] == duplicate_id])

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.461,1,-6.746,0,0.143,0.0322,0.000001,0.358,0.715,87.917,4,acoustic
62102,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.461,1,-6.746,0,0.143,0.0322,0.000001,0.358,0.715,87.917,4,j-pop
99152,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.461,1,-6.746,0,0.143,0.0322,0.000001,0.358,0.715,87.917,4,singer-songwriter
102151,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.461,1,-6.746,0,0.143,0.0322,0.000001,0.358,0.715,87.917,4,songwriter

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.42,0.166,1,-17.235,1,0.0763,0.924,0.000006,0.101,0.267,77.489,4,acoustic
15190,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.42,0.166,1,-17.235,1,0.0763,0.924,0.000006,0.101,0.267,77.489,4,chill

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,0.481,6,-8.807,1,0.105,0.289,0.0,0.189,0.666,98.017,4,acoustic
56777,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,0.481,6,-8.807,1,0.105,0.289,0.0,0.189,0.666,98.017,4,indie-pop

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.147,2,-8.822,1,0.0355,0.857,0.000003,0.0913,0.0765,141.284,3,acoustic
79104,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.147,2,-8.822,1,0.0355,0.857,0.000003,0.0913,0.0765,141.284,3,piano

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.96,4,acoustic
91904,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.559,0.0,0.0973,0.712,150.96,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
9,7k9GuJYLp2AzqokyEdwEw2,Ross Copperman,Hunger,Hunger,56,205594,False,0.442,0.632,1,-6.77,1,0.0295,0.426,0.00419,0.0735,0.196,78.899,4,acoustic
79110,7k9GuJYLp2AzqokyEdwEw2,Ross Copperman,Hunger,Hunger,56,205594,False,0.442,0.632,1,-6.77,1,0.0295,0.426,0.00419,0.0735,0.196,78.899,4,piano

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
12,4ptDJbJl35d7gQfeNteBwp,Dan Berk,Solo,Solo,52,198712,False,0.489,0.314,7,-9.245,0,0.0331,0.749,0.0,0.113,0.607,124.234,4,acoustic
15191,4ptDJbJl35d7gQfeNteBwp,Dan Berk,Solo,Solo,52,198712,False,0.489,0.314,7,-9.245,0,0.0331,0.749,0.0,0.113,0.607,124.234,4,chill

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
13,0X9MxHR1rTkEHDjp95F2OO,Anna Hamilton,Bad Liar,Bad Liar,62,248448,False,0.691,0.234,3,-6.441,1,0.0285,0.777,0.0,0.12,0.209,87.103,4,acoustic
15088,0X9MxHR1rTkEHDjp95F2OO,Anna Hamilton,Bad Liar,Bad Liar,62,248448,False,0.691,0.234,3,-6.441,1,0.0285,0.777,0.0,0.12,0.209,87.103,4,chill

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
16,6xKeQgzfjixSUld14qUezm,Andrew Foy;Renee Foy,ily (i love you baby),ily (i love you baby),56,129750,False,0.706,0.112,2,-18.098,1,0.0391,0.827,0.000004,0.125,0.414,110.154,4,acoustic
45002,6xKeQgzfjixSUld14qUezm,Andrew Foy;Renee Foy,ily (i love you baby),ily (i love you baby),56,129750,False,0.706,0.112,2,-18.098,1,0.0391,0.827,0.000004,0.125,0.414,110.154,4,guitar

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
17,4Yo0igmcoNyat1secaH0OD,Andrew Foy;Renee Foy,At My Worst,At My Worst,54,169728,False,0.795,0.0841,10,-18.09,0,0.0461,0.742,0.000012,0.0853,0.609,91.803,4,acoustic
45004,4Yo0igmcoNyat1secaH0OD,Andrew Foy;Renee Foy,At My Worst,At My Worst,54,169728,False,0.795,0.0841,10,-18.09,0,0.0461,0.742,0.000012,0.0853,0.609,91.803,4,guitar

In [19]:
non_identical_number = 0
special_ids = []

df_genre_dropped = df.drop(columns=["track_genre"])

for repeated_id in repeated_track_rows["track_id"].head(1000):
    id_group = df_genre_dropped[df["track_id"] == repeated_id]

    is_all_identical = all(id_group.duplicated(keep=False))

    if not is_all_identical:
        non_identical_number += 1
        special_ids.append(repeated_id)

print(non_identical_number)

28

Initial inspection of several duplicated track_id values suggested that repeated tracks differed only in the track_genre column. To verify this observation, the first 1,000 duplicated track_id groups were examined programmatically. 

Among the first 1000 duplicated track_id groups inspected programmatically, only 28 groups contained differences beyond `track_genre`.

In [21]:
for special_id in special_ids:
    display(df[df["track_id"] == special_id ])

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
29,2qESE1ZeWly7I3YjyTXmXh,Jason Mraz,Perfect Christmas Hits,Winter Wonderland,0,131760,False,0.62,0.309,5,-9.209,1,0.0495,0.788,0.0,0.146,0.664,145.363,4,acoustic
91665,2qESE1ZeWly7I3YjyTXmXh,Jason Mraz,Perfect Christmas Hits,Winter Wonderland,1,131760,False,0.62,0.309,5,-9.209,1,0.0495,0.788,0.0,0.146,0.664,145.363,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
130,72R0X0h8YaxYNpegeoOl0M,Parachute,The Way It Was,Kiss Me Slowly,61,235813,False,0.47,0.801,9,-6.426,1,0.0352,0.0758,0.000035,0.218,0.431,173.92,4,acoustic
85311,72R0X0h8YaxYNpegeoOl0M,Parachute,The Way It Was,Kiss Me Slowly,60,235813,False,0.47,0.801,9,-6.426,1,0.0352,0.0758,0.000035,0.218,0.431,173.92,4,punk-rock
86414,72R0X0h8YaxYNpegeoOl0M,Parachute,The Way It Was,Kiss Me Slowly,61,235813,False,0.47,0.801,9,-6.426,1,0.0352,0.0758,0.000035,0.218,0.431,173.92,4,punk

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1013,3BGxXQJWeLAEcwNKRFUxYA,BaianaSystem;BNegão,ATO 1: Navio Pirata,Reza Forte,38,232826,False,0.844,0.915,0,-4.06,0,0.129,0.393,0.00238,0.0847,0.872,145.997,4,afrobeat
28194,3BGxXQJWeLAEcwNKRFUxYA,BaianaSystem;BNegão,ATO 1: Navio Pirata,Reza Forte,38,232826,False,0.844,0.915,0,-4.06,0,0.129,0.393,0.00238,0.0847,0.872,145.997,4,dub
96906,3BGxXQJWeLAEcwNKRFUxYA,BaianaSystem;BNegão,ATO 1: Navio Pirata,Reza Forte,37,232826,False,0.844,0.915,0,-4.06,0,0.129,0.393,0.00238,0.0847,0.872,145.997,4,samba

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1039,2zQt5C0AIv27RhfJCRZdZ4,BaianaSystem,Duas Cidades,"Jah Jah Revolta, Pt. 2",39,309493,False,0.776,0.8,8,-4.704,0,0.0438,0.00631,0.0731,0.35,0.583,143.989,4,afrobeat
28196,2zQt5C0AIv27RhfJCRZdZ4,BaianaSystem,Duas Cidades,"Jah Jah Revolta, Pt. 2",39,309493,False,0.776,0.8,8,-4.704,0,0.0438,0.00631,0.0731,0.35,0.583,143.989,4,dub
96815,2zQt5C0AIv27RhfJCRZdZ4,BaianaSystem,Duas Cidades,"Jah Jah Revolta, Pt. 2",38,309493,False,0.776,0.8,8,-4.704,0,0.0438,0.00631,0.0731,0.35,0.583,143.989,4,samba

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1096,3MZm4t1kRJ2e5JyaYQpjrF,Jackie Mittoo,The Keyboard King at Studio One,Black Organ,34,191506,False,0.837,0.598,1,-9.047,0,0.181,0.391,0.238,0.0598,0.983,145.219,4,afrobeat
28345,3MZm4t1kRJ2e5JyaYQpjrF,Jackie Mittoo,The Keyboard King at Studio One,Black Organ,34,191506,False,0.837,0.598,1,-9.047,0,0.181,0.391,0.238,0.0598,0.983,145.219,4,dub
100861,3MZm4t1kRJ2e5JyaYQpjrF,Jackie Mittoo,The Keyboard King at Studio One,Black Organ,33,191506,False,0.837,0.598,1,-9.047,0,0.181,0.391,0.238,0.0598,0.983,145.219,4,ska

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2007,0y1QJc3SJVPKJ1OvFmFqe6,KALEO,A/B,Way down We Go,78,213706,False,0.489,0.505,10,-8.022,0,0.117,0.579,0.000333,0.104,0.337,163.255,4,alt-rock
3051,0y1QJc3SJVPKJ1OvFmFqe6,KALEO,A/B,Way down We Go,78,213706,False,0.489,0.505,10,-8.022,0,0.117,0.579,0.000333,0.104,0.337,163.255,4,alternative
57162,0y1QJc3SJVPKJ1OvFmFqe6,KALEO,A/B,Way down We Go,78,213706,False,0.489,0.505,10,-8.022,0,0.117,0.579,0.000333,0.104,0.337,163.255,4,indie
91256,0y1QJc3SJVPKJ1OvFmFqe6,KALEO,A/B,Way down We Go,77,213706,False,0.489,0.505,10,-8.022,0,0.117,0.579,0.000333,0.104,0.337,163.255,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2012,7uCBGNn991AM68fR4tSDco,The Score,Carry On,Born For This,69,237375,False,0.411,0.675,5,-6.251,0,0.0591,0.063,0.0,0.092,0.545,130.134,4,alt-rock
3104,7uCBGNn991AM68fR4tSDco,The Score,Carry On,Born For This,69,237375,False,0.411,0.675,5,-6.251,0,0.0591,0.063,0.0,0.092,0.545,130.134,4,alternative
91407,7uCBGNn991AM68fR4tSDco,The Score,Carry On,Born For This,68,237375,False,0.411,0.675,5,-6.251,0,0.0591,0.063,0.0,0.092,0.545,130.134,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2014,75fT19n6ZQHr67Mkh86qfD,Red Hot Chili Peppers,Rock Brandneu,Tippa My Tongue,2,260808,False,0.573,0.913,5,-6.52,0,0.0409,0.00861,0.0273,0.114,0.795,88.418,4,alt-rock
3014,75fT19n6ZQHr67Mkh86qfD,Red Hot Chili Peppers,Rock Brandneu,Tippa My Tongue,2,260808,False,0.573,0.913,5,-6.52,0,0.0409,0.00861,0.0273,0.114,0.795,88.418,4,alternative
37029,75fT19n6ZQHr67Mkh86qfD,Red Hot Chili Peppers,Rock Brandneu,Tippa My Tongue,2,260808,False,0.573,0.913,5,-6.52,0,0.0409,0.00861,0.0273,0.114,0.795,88.418,4,funk
71015,75fT19n6ZQHr67Mkh86qfD,Red Hot Chili Peppers,Rock Brandneu,Tippa My Tongue,2,260808,False,0.573,0.913,5,-6.52,0,0.0409,0.00861,0.0273,0.114,0.795,88.418,4,metal
91118,75fT19n6ZQHr67Mkh86qfD,Red Hot Chili Peppers,Rock Brandneu,Tippa My Tongue,3,260808,False,0.573,0.913,5,-6.52,0,0.0409,0.00861,0.0273,0.114,0.795,88.418,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2018,1yZWmKmLfTrFCxHvhFsdoN,The Killers;Phoebe Bridgers,The Greatest Rock Tunes 2022,Runaway Horses - Abridged,0,204466,False,0.499,0.223,9,-15.253,1,0.0338,0.912,0.0,0.0962,0.304,129.291,5,alt-rock
3021,1yZWmKmLfTrFCxHvhFsdoN,The Killers;Phoebe Bridgers,The Greatest Rock Tunes 2022,Runaway Horses - Abridged,0,204466,False,0.499,0.223,9,-15.253,1,0.0338,0.912,0.0,0.0962,0.304,129.291,5,alternative
91224,1yZWmKmLfTrFCxHvhFsdoN,The Killers;Phoebe Bridgers,The Greatest Rock Tunes 2022,Runaway Horses - Abridged,1,204466,False,0.499,0.223,9,-15.253,1,0.0338,0.912,0.0,0.0962,0.304,129.291,5,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2023,1bOENKlPYEDXyH9kLFUsnj,Nickelback,Timeless Rock Hits,Animals,3,185906,False,0.569,0.963,7,-3.069,1,0.0593,0.000787,0.0256,0.22,0.82,76.995,4,alt-rock
3072,1bOENKlPYEDXyH9kLFUsnj,Nickelback,Timeless Rock Hits,Animals,3,185906,False,0.569,0.963,7,-3.069,1,0.0593,0.000787,0.0256,0.22,0.82,76.995,4,alternative
44026,1bOENKlPYEDXyH9kLFUsnj,Nickelback,Timeless Rock Hits,Animals,3,185906,False,0.569,0.963,7,-3.069,1,0.0593,0.000787,0.0256,0.22,0.82,76.995,4,grunge
71021,1bOENKlPYEDXyH9kLFUsnj,Nickelback,Timeless Rock Hits,Animals,3,185906,False,0.569,0.963,7,-3.069,1,0.0593,0.000787,0.0256,0.22,0.82,76.995,4,metal
91327,1bOENKlPYEDXyH9kLFUsnj,Nickelback,Timeless Rock Hits,Animals,4,185906,False,0.569,0.963,7,-3.069,1,0.0593,0.000787,0.0256,0.22,0.82,76.995,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2030,6ehaWPjsNSf5HWOXTEFSUi,The Killers,Rock Workout 2023,Somebody Told Me,0,200946,False,0.508,0.981,10,-3.23,0,0.0779,0.000082,0.000449,0.0555,0.746,138.011,4,alt-rock
3031,6ehaWPjsNSf5HWOXTEFSUi,The Killers,Rock Workout 2023,Somebody Told Me,0,200946,False,0.508,0.981,10,-3.23,0,0.0779,0.000082,0.000449,0.0555,0.746,138.011,4,alternative
20990,6ehaWPjsNSf5HWOXTEFSUi,The Killers,Rock Workout 2023,Somebody Told Me,0,200946,False,0.508,0.981,10,-3.23,0,0.0779,0.000082,0.000449,0.0555,0.746,138.011,4,dance
91236,6ehaWPjsNSf5HWOXTEFSUi,The Killers,Rock Workout 2023,Somebody Told Me,1,200946,False,0.508,0.981,10,-3.23,0,0.0779,0.000082,0.000449,0.0555,0.746,138.011,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2034,0v8tmDMQrTMavluubqAJo4,Red Hot Chili Peppers,80s Bangers Vol. 2,Higher Ground - Remastered,1,202053,False,0.476,0.979,4,-3.504,0,0.133,0.00142,0.00686,0.0944,0.394,140.408,4,alt-rock
3022,0v8tmDMQrTMavluubqAJo4,Red Hot Chili Peppers,80s Bangers Vol. 2,Higher Ground - Remastered,1,202053,False,0.476,0.979,4,-3.504,0,0.133,0.00142,0.00686,0.0944,0.394,140.408,4,alternative
37048,0v8tmDMQrTMavluubqAJo4,Red Hot Chili Peppers,80s Bangers Vol. 2,Higher Ground - Remastered,1,202053,False,0.476,0.979,4,-3.504,0,0.133,0.00142,0.00686,0.0944,0.394,140.408,4,funk
71044,0v8tmDMQrTMavluubqAJo4,Red Hot Chili Peppers,80s Bangers Vol. 2,Higher Ground - Remastered,1,202053,False,0.476,0.979,4,-3.504,0,0.133,0.00142,0.00686,0.0944,0.394,140.408,4,metal
91130,0v8tmDMQrTMavluubqAJo4,Red Hot Chili Peppers,80s Bangers Vol. 2,Higher Ground - Remastered,4,202053,False,0.476,0.979,4,-3.504,0,0.133,0.00142,0.00686,0.0944,0.394,140.408,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2060,7oMO1B9CB4ZPYPLeVe32OY,R.E.M.,90's Music Grandi Successi,Losing My Religion,0,268426,False,0.666,0.854,9,-5.051,0,0.0295,0.179,0.000001,0.0986,0.803,125.637,4,alt-rock
3105,7oMO1B9CB4ZPYPLeVe32OY,R.E.M.,90's Music Grandi Successi,Losing My Religion,0,268426,False,0.666,0.854,9,-5.051,0,0.0295,0.179,0.000001,0.0986,0.803,125.637,4,alternative
56196,7oMO1B9CB4ZPYPLeVe32OY,R.E.M.,90's Music Grandi Successi,Losing My Religion,0,268426,False,0.666,0.854,9,-5.051,0,0.0295,0.179,0.000001,0.0986,0.803,125.637,4,indie-pop
57393,7oMO1B9CB4ZPYPLeVe32OY,R.E.M.,90's Music Grandi Successi,Losing My Religion,0,268426,False,0.666,0.854,9,-5.051,0,0.0295,0.179,0.000001,0.0986,0.803,125.637,4,indie
91465,7oMO1B9CB4ZPYPLeVe32OY,R.E.M.,90's Music Grandi Successi,Losing My Religion,1,268426,False,0.666,0.854,9,-5.051,0,0.0295,0.179,0.000001,0.0986,0.803,125.637,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2072,1l1ra0gsPlpnDOc4HdkKZU,Weezer,Emo Christmas 2022,O Come All Ye Faithful,0,124653,False,0.516,0.818,11,-6.076,1,0.0393,0.00701,0.0,0.337,0.769,121.907,4,alt-rock
3125,1l1ra0gsPlpnDOc4HdkKZU,Weezer,Emo Christmas 2022,O Come All Ye Faithful,0,124653,False,0.516,0.818,11,-6.076,1,0.0393,0.00701,0.0,0.337,0.769,121.907,4,alternative
82008,1l1ra0gsPlpnDOc4HdkKZU,Weezer,Emo Christmas 2022,O Come All Ye Faithful,0,124653,False,0.516,0.818,11,-6.076,1,0.0393,0.00701,0.0,0.337,0.769,121.907,4,power-pop
91425,1l1ra0gsPlpnDOc4HdkKZU,Weezer,Emo Christmas 2022,O Come All Ye Faithful,1,124653,False,0.516,0.818,11,-6.076,1,0.0393,0.00701,0.0,0.337,0.769,121.907,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2081,3kQhWtoluFHPbcBC6gyYrZ,Zoé,tardes tranqui,Arrullo De Estrellas,0,252986,False,0.462,0.765,5,-7.011,1,0.036,0.324,0.231,0.0757,0.399,81.513,4,alt-rock
3196,3kQhWtoluFHPbcBC6gyYrZ,Zoé,tardes tranqui,Arrullo De Estrellas,0,252986,False,0.462,0.765,5,-7.011,1,0.036,0.324,0.231,0.0757,0.399,81.513,4,alternative
57445,3kQhWtoluFHPbcBC6gyYrZ,Zoé,tardes tranqui,Arrullo De Estrellas,0,252986,False,0.462,0.765,5,-7.011,1,0.036,0.324,0.231,0.0757,0.399,81.513,4,indie
67532,3kQhWtoluFHPbcBC6gyYrZ,Zoé,tardes tranqui,Arrullo De Estrellas,0,252986,False,0.462,0.765,5,-7.011,1,0.036,0.324,0.231,0.0757,0.399,81.513,4,latin
91477,3kQhWtoluFHPbcBC6gyYrZ,Zoé,tardes tranqui,Arrullo De Estrellas,1,252986,False,0.462,0.765,5,-7.011,1,0.036,0.324,0.231,0.0757,0.399,81.513,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2112,6VuztO5yaKP4VjqSkZxpan,Ashes Remain,What I've Become,On My Own,69,172960,False,0.361,0.871,8,-4.313,1,0.0393,0.0119,0.0,0.318,0.575,176.026,4,alt-rock
3221,6VuztO5yaKP4VjqSkZxpan,Ashes Remain,What I've Become,On My Own,69,172960,False,0.361,0.871,8,-4.313,1,0.0393,0.0119,0.0,0.318,0.575,176.026,4,alternative
91767,6VuztO5yaKP4VjqSkZxpan,Ashes Remain,What I've Become,On My Own,68,172960,False,0.361,0.871,8,-4.313,1,0.0393,0.0119,0.0,0.318,0.575,176.026,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2119,42Jkqzhm5Y7ab7f1d22GTq,Andrés Calamaro;Sebastian Yatra;Leiva;Ivan Fer...,Pañuelos al viento,Paloma,2,285024,False,0.727,0.382,9,-9.145,1,0.0314,0.809,0.0,0.0998,0.828,115.003,4,alt-rock
3328,42Jkqzhm5Y7ab7f1d22GTq,Andrés Calamaro;Sebastian Yatra;Leiva;Ivan Fer...,Pañuelos al viento,Paloma,2,285024,False,0.727,0.382,9,-9.145,1,0.0314,0.809,0.0,0.0998,0.828,115.003,4,alternative
67616,42Jkqzhm5Y7ab7f1d22GTq,Andrés Calamaro;Sebastian Yatra;Leiva;Ivan Fer...,Pañuelos al viento,Paloma,2,285024,False,0.727,0.382,9,-9.145,1,0.0314,0.809,0.0,0.0998,0.828,115.003,4,latin
91772,42Jkqzhm5Y7ab7f1d22GTq,Andrés Calamaro;Sebastian Yatra;Leiva;Ivan Fer...,Pañuelos al viento,Paloma,3,285024,False,0.727,0.382,9,-9.145,1,0.0314,0.809,0.0,0.0998,0.828,115.003,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2140,582QmuQapDg7uo1jcAKsgN,Megadeth,Release Your ANGER,Holy Wars...The Punishment Due - Remastered,0,392600,False,0.327,0.985,11,-3.941,1,0.151,0.00177,0.108,0.351,0.218,125.232,4,alt-rock
3299,582QmuQapDg7uo1jcAKsgN,Megadeth,Release Your ANGER,Holy Wars...The Punishment Due - Remastered,0,392600,False,0.327,0.985,11,-3.941,1,0.151,0.00177,0.108,0.351,0.218,125.232,4,alternative
47083,582QmuQapDg7uo1jcAKsgN,Megadeth,Release Your ANGER,Holy Wars...The Punishment Due - Remastered,0,392600,False,0.327,0.985,11,-3.941,1,0.151,0.00177,0.108,0.351,0.218,125.232,4,hard-rock
71093,582QmuQapDg7uo1jcAKsgN,Megadeth,Release Your ANGER,Holy Wars...The Punishment Due - Remastered,0,392600,False,0.327,0.985,11,-3.941,1,0.151,0.00177,0.108,0.351,0.218,125.232,4,metal
91698,582QmuQapDg7uo1jcAKsgN,Megadeth,Release Your ANGER,Holy Wars...The Punishment Due - Remastered,1,392600,False,0.327,0.985,11,-3.941,1,0.151,0.00177,0.108,0.351,0.218,125.232,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2153,14dJexYlvd3t3XAtD1pYW1,The 1975,Being Funny In A Foreign Language,Oh Caroline,76,212568,False,0.646,0.85,2,-5.466,1,0.0428,0.363,0.00004,0.0994,0.819,96.538,4,alt-rock
3303,14dJexYlvd3t3XAtD1pYW1,The 1975,Being Funny In A Foreign Language,Oh Caroline,76,212568,False,0.646,0.85,2,-5.466,1,0.0428,0.363,0.00004,0.0994,0.819,96.538,4,alternative
91754,14dJexYlvd3t3XAtD1pYW1,The 1975,Being Funny In A Foreign Language,Oh Caroline,77,212568,False,0.646,0.85,2,-5.466,1,0.0428,0.363,0.00004,0.0994,0.819,96.538,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2156,0fYVliAYKHuPmECRs1pbRf,X Ambassadors,VHS,Renegades,76,195200,False,0.526,0.862,2,-6.003,1,0.0905,0.0144,0.0597,0.229,0.528,90.052,4,alt-rock
3310,0fYVliAYKHuPmECRs1pbRf,X Ambassadors,VHS,Renegades,76,195200,False,0.526,0.862,2,-6.003,1,0.0905,0.0144,0.0597,0.229,0.528,90.052,4,alternative
91763,0fYVliAYKHuPmECRs1pbRf,X Ambassadors,VHS,Renegades,75,195200,False,0.526,0.862,2,-6.003,1,0.0905,0.0144,0.0597,0.229,0.528,90.052,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2176,1lYHv3SEkE6wKfZRe0HMOG,Counting Crows,Christmas Songs 2022,A Long December,1,297293,False,0.403,0.59,5,-5.941,1,0.0284,0.508,0.00548,0.272,0.393,141.649,4,alt-rock
3333,1lYHv3SEkE6wKfZRe0HMOG,Counting Crows,Christmas Songs 2022,A Long December,1,297293,False,0.403,0.59,5,-5.941,1,0.0284,0.508,0.00548,0.272,0.393,141.649,4,alternative
91884,1lYHv3SEkE6wKfZRe0HMOG,Counting Crows,Christmas Songs 2022,A Long December,2,297293,False,0.403,0.59,5,-5.941,1,0.0284,0.508,0.00548,0.272,0.393,141.649,4,rock

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2322,1EWRXz6c0WPKae8vziEnZi,Chris Tomlin,Santa's Christmas List,Joy To The World (Unspeakable Joy),1,230720,False,0.418,0.876,2,-5.157,1,0.0529,0.00187,0.0,0.829,0.341,128.033,4,alt-rock
3423,1EWRXz6c0WPKae8vziEnZi,Chris Tomlin,Santa's Christmas List,Joy To The World (Unspeakable Joy),1,230720,False,0.418,0.876,2,-5.157,1,0.0529,0.00187,0.0,0.829,0.341,128.033,4,alternative
113037,1EWRXz6c0WPKae8vziEnZi,Chris Tomlin,Santa's Christmas List,Joy To The World (Unspeakable Joy),3,230720,False,0.418,0.876,2,-5.157,1,0.0529,0.00187,0.0,0.829,0.341,128.033,4,world-music

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2324,1GN7Kn9Hr4pOpVVxBL1ZUD,Chris Tomlin;Lauren Daigle,Christmas Dinner,Noel - Live,0,257720,False,0.349,0.261,10,-9.478,0,0.0306,0.748,0.0,0.104,0.103,137.954,4,alt-rock
3429,1GN7Kn9Hr4pOpVVxBL1ZUD,Chris Tomlin;Lauren Daigle,Christmas Dinner,Noel - Live,0,257720,False,0.349,0.261,10,-9.478,0,0.0306,0.748,0.0,0.104,0.103,137.954,4,alternative
113036,1GN7Kn9Hr4pOpVVxBL1ZUD,Chris Tomlin;Lauren Daigle,Christmas Dinner,Noel - Live,1,257720,False,0.349,0.261,10,-9.478,0,0.0306,0.748,0.0,0.104,0.103,137.954,4,world-music

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2421,4k2AjlWruIygEiZyJEy01I,Os Paralamas Do Sucesso,Acústico (Live),Tendo A Lua - Ao Vivo,51,200826,False,0.492,0.794,5,-5.823,1,0.046,0.196,0.000003,0.873,0.683,167.815,4,alt-rock
3737,4k2AjlWruIygEiZyJEy01I,Os Paralamas Do Sucesso,Acústico (Live),Tendo A Lua - Ao Vivo,51,200826,False,0.492,0.794,5,-5.823,1,0.046,0.196,0.000003,0.873,0.683,167.815,4,alternative
9115,4k2AjlWruIygEiZyJEy01I,Os Paralamas Do Sucesso,Acústico (Live),Tendo A Lua - Ao Vivo,51,200826,False,0.492,0.794,5,-5.823,1,0.046,0.196,0.000003,0.873,0.683,167.815,4,brazil
74008,4k2AjlWruIygEiZyJEy01I,Os Paralamas Do Sucesso,Acústico (Live),Tendo A Lua - Ao Vivo,51,200826,False,0.492,0.794,5,-5.823,1,0.046,0.196,0.000003,0.873,0.683,167.815,4,mpb
87104,4k2AjlWruIygEiZyJEy01I,Os Paralamas Do Sucesso,Acústico (Live),Tendo A Lua - Ao Vivo,50,200826,False,0.492,0.794,5,-5.823,1,0.046,0.196,0.000003,0.873,0.683,167.815,4,r-n-b

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2486,6VQW8Ye28Crwz90BIexsrF,Bersuit Vergarabat,Triste Hora,Vuelos,0,264586,False,0.423,0.493,2,-9.569,0,0.0374,0.1,0.000006,0.0797,0.522,167.708,4,alt-rock
3890,6VQW8Ye28Crwz90BIexsrF,Bersuit Vergarabat,Triste Hora,Vuelos,0,264586,False,0.423,0.493,2,-9.569,0,0.0374,0.1,0.000006,0.0797,0.522,167.708,4,alternative
100023,6VQW8Ye28Crwz90BIexsrF,Bersuit Vergarabat,Triste Hora,Vuelos,1,264586,False,0.423,0.493,2,-9.569,0,0.0374,0.1,0.000006,0.0797,0.522,167.708,4,ska

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2624,3QoydK0LFOpK0JnfIpCffR,Charlie Brown Jr.,Acústico (Ao Vivo),O Coro Vai Come - Ao Vivo,48,128106,False,0.511,0.981,0,-5.329,0,0.0579,0.0301,0.0612,0.747,0.896,172.968,4,alt-rock
9418,3QoydK0LFOpK0JnfIpCffR,Charlie Brown Jr.,Acústico (Ao Vivo),O Coro Vai Come - Ao Vivo,48,128106,False,0.511,0.981,0,-5.329,0,0.0579,0.0301,0.0612,0.747,0.896,172.968,4,brazil
47230,3QoydK0LFOpK0JnfIpCffR,Charlie Brown Jr.,Acústico (Ao Vivo),O Coro Vai Come - Ao Vivo,48,128106,False,0.511,0.981,0,-5.329,0,0.0579,0.0301,0.0612,0.747,0.896,172.968,4,hard-rock
87209,3QoydK0LFOpK0JnfIpCffR,Charlie Brown Jr.,Acústico (Ao Vivo),O Coro Vai Come - Ao Vivo,47,128106,False,0.511,0.981,0,-5.329,0,0.0579,0.0301,0.0612,0.747,0.896,172.968,4,r-n-b

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2628,7sC2sL3Q5cZswDQJfnlfOt,Charlie Brown Jr.,100% Charlie Brown Jr - Abalando A Sua Fábrica,Tudo Pro Alto,48,203093,False,0.215,0.945,10,-7.201,0,0.0798,0.000639,0.453,0.204,0.603,179.079,4,alt-rock
9413,7sC2sL3Q5cZswDQJfnlfOt,Charlie Brown Jr.,100% Charlie Brown Jr - Abalando A Sua Fábrica,Tudo Pro Alto,48,203093,False,0.215,0.945,10,-7.201,0,0.0798,0.000639,0.453,0.204,0.603,179.079,4,brazil
47229,7sC2sL3Q5cZswDQJfnlfOt,Charlie Brown Jr.,100% Charlie Brown Jr - Abalando A Sua Fábrica,Tudo Pro Alto,48,203093,False,0.215,0.945,10,-7.201,0,0.0798,0.000639,0.453,0.204,0.603,179.079,4,hard-rock
87206,7sC2sL3Q5cZswDQJfnlfOt,Charlie Brown Jr.,100% Charlie Brown Jr - Abalando A Sua Fábrica,Tudo Pro Alto,47,203093,False,0.215,0.945,10,-7.201,0,0.0798,0.000639,0.453,0.204,0.603,179.079,4,r-n-b

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2660,5d9RSSwDvlTyuwfmeafUah,Phil Wickham,Living Hope,Living Hope,55,327000,False,0.292,0.535,3,-6.892,1,0.0393,0.0355,0.0,0.0977,0.316,143.949,4,alt-rock
113012,5d9RSSwDvlTyuwfmeafUah,Phil Wickham,Living Hope,Living Hope,54,327000,False,0.292,0.535,3,-6.892,1,0.0393,0.0355,0.0,0.0977,0.316,143.949,4,world-music

Among the first 1,000 duplicated `track_id` groups inspected, the only observed differences outside `track_genre` were in the `popularity` column.

One possible explanation is that the dataset creator queried the Spotify API at different times. Since Spotify's popularity metric changes over time, repeated observations of the same track may have different popularity values while the audio features remain unchanged. This explanation is plausible but cannot be confirmed from the available dataset documentation.

In [19]:
non_identical_number = 0

df_genre_pop_dropped = df.drop(columns=["track_genre", "popularity"])
for special_id in special_ids:
    id_group = df_genre_pop_dropped[df["track_id"] == special_id] # rows for a specific duplicated ID 
    is_all_identical = all(id_group.duplicated(keep=False)) # See if the rows w/o genre identical
    if is_all_identical == False:
        non_identical_number += 1
print(non_identical_number)

0

In [37]:
df[df["track_id"] == "0CDucx9lKxuCZplLXUz0iX"]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
1874,0CDucx9lKxuCZplLXUz0iX,Buena Onda Reggae Club,Disco 2,Song for Rollins,16,219346,False,0.841,0.577,0,-7.544,1,0.0438,0.238,0.86,0.0571,0.843,90.522,4,afrobeat
1925,0CDucx9lKxuCZplLXUz0iX,Buena Onda Reggae Club,Disco 2,Song for Rollins,16,219346,False,0.841,0.577,0,-7.544,1,0.0438,0.238,0.86,0.0571,0.843,90.522,4,afrobeat

**Conclusion:** The duplicate `track_id` investigation suggests that repeated rows are generally intentional rather than erroneous. Most repeated observations represent the same track assigned to multiple genres, while a small subset also differs in popularity. Therefore, repeated `track_ids` should not be treated as ordinary duplicate records without considering the analytical objectives of the project.